name: npm packager build

on:
  release:
    types: [published]
jobs:
  build-npm-packager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bduff9/use-npmrc@v1.2
        with:
          dot-npmrc: ${{ secrets.DOT_NPMRC }}
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
